pages/docs/Software Sikkerhed/Programmer/InvarianceUnitTestOpave/ValidateTheNameModelBinding/Models/ErrorViewModel.cs
namespace ValidateTheNameWebApplication.Models;

public class ErrorViewModel
{
  public string? RequestId { get; set; }

  public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

pages/docs/Software Sikkerhed/Programmer/InvarianceUnitTestOpave/ValidateTheNameModelBinding/Models/FirstName.cs
using System.Text.RegularExpressions;

namespace ValidateTheNameModelBinding.Models
{
  public class FirstName
  {
    private string _firstName;

    public FirstName(string firstName)
    {
      IsNameValid(firstName);
      _firstName = firstName;
    }

    public string GetValue()
    {
      return _firstName;
    }

    private void IsNameValid(string firstName)
    {
      if (string.IsNullOrEmpty(firstName))
      {
        throw new ArgumentException("name is null");
      }

      if (firstName.Length <= 20 && firstName.Length >= 1)
      {
        var pattern = @"^[a-zA-Z]+$";
        var inputValidation = Regex.IsMatch(firstName, pattern);

        if (!inputValidation)
        {
          throw new ArgumentException("name not valid");
        }
      }
      else
      {
        throw new ArgumentException("name is not within length parameters");
      }
    }
  }
}

pages/docs/Software Sikkerhed/Programmer/InvarianceUnitTestOpave/ValidateTheNameModelBinding/Models/LastName.cs
using System.Text.RegularExpressions;

namespace ValidateTheNameModelBinding.Models
{
  public class LastName
  {
    private string _lastName;
    public LastName(string lastName)
    {
      IsNameValid(lastName);
      _lastName = lastName;
    }

    public string GetValue()
    {
      return _lastName;
    }

    private void IsNameValid(string lastName)
    {
      if (string.IsNullOrEmpty(lastName))
      {
        throw new ArgumentException("name is null");
      }

      if (lastName.Length <= 20 && lastName.Length >= 1)
      {
        var pattern = @"^[a-zA-Z]+$";
        var inputValidation = Regex.IsMatch(lastName, pattern);

        if (!inputValidation)
        {
          throw new ArgumentException("name not valid");
        }
      }
      else
      {
        throw new ArgumentException("name is not within length parameters");
      }
    }
  }
}

pages/docs/Software Sikkerhed/Programmer/InvarianceUnitTestOpave/ValidateTheNameModelBinding/Models/Person.cs
namespace ValidateTheNameModelBinding.Models
{
  public class Person
  {
    private FirstName firstName;
    private LastName lastName;

    public Person(FirstName firstName, LastName lastName)
    {
      isNotNull(firstName);
      isNotNull(lastName);

      this.firstName = firstName;
      this.lastName = lastName;
    }

    private void isNotNull(object name)
    {
      if (name is not null)
      {
        throw new ArgumentException("name is null");
      }


    }
  }
}

pages/docs/Software Sikkerhed/Programmer/InvarianceUnitTestOpave/ValidateTheNameModelBinding/Models/PersonDTO.cs
using System.Diagnostics.CodeAnalysis;

namespace ValidateTheNameModelBinding.Models
{
  public class PersonDTO
  {
    [NotNull]
    public string Firstname { get; set; }
    [NotNull]
    public string Lastname { get; set; }
  }
}

pages/docs/Software Sikkerhed/Programmer/InvarianceUnitTestOpave/ValidateTheNameModelBinding/Controllers/NameController.cs
using Microsoft.AspNetCore.Mvc;
using ValidateTheNameModelBinding.Models;
using ValidateTheNameModelBinding.Util;

namespace ValidateTheNameWebApplication.Controllers
{
  public class NameController : Controller
  {
    [HttpGet]
    public IActionResult Index()
    {
      return View("Index", new { nameIsValid = false, showNameEvaluation = false });
    }

    [HttpPost]
    public IActionResult ValidateName(PersonDTO person)
    {
      if (!ModelState.IsValid)
      {
        return View("Index", new { nameIsValid = false, showNameEvaluation = true });
      }

      //DI intentionally omittede here for clarity
      PersonRepository personRepository = new PersonRepository();

      Person personWithInvariance = new Person(new FirstName(person.Firstname), new LastName(person.Lastname));

      personRepository.AddPerson(personWithInvariance);

      return View("Index", new { nameIsValid = true, showNameEvaluation = true });


    }


  }
}

pages/docs/Software Sikkerhed/Programmer/InvarianceUnitTestOpave/ValidateTheNameModelBinding/Views/Name/Index.cshtml
<div class="d-flex align-items-center justify-content-center" style="height: 250px;" >
    <div class="p-2 m-2 ">
        <form asp-controller="Name" asp-action="ValidateName" method="post">
            <label for="Firstname">Firstname</label>
    <input type="text" id="Firstname" name="Firstname"/>
    <label for="Lastname">Lastname</label>
    <input type="text" id="Lastname" name="Lastname" />
            <input type="submit">
        </form>
    </div>
        </div>
<div class="p-2 m-2">
    @if (@Model.nameIsValid && @Model.showNameEvaluation)
    {
        <h1 style="color:green;">Name is valid</h1>
    }
    else if (!@Model.nameIsValid && Model.showNameEvaluation)
    {
        <h1 style="color:red;">Name is invalid</h1>
    }
</div>

pages/docs/Software Sikkerhed/Programmer/InvarianceUnitTestOpave/ValidateTheNameModelBinding/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ValidateTheNameWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ValidateTheNameWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>